export default function () {
  return {
    status: '',
    token: localStorage.getItem('tokenchi') || '',
    user : {},
    pedido:[],
    usuarios:false,
    clientes:false,
    productos:false,
    inventario:false,
    ventadetalle:false,
    historialventadetalle:false,
    ventalocal:false,
    historialventalocal:false,
    empleados:false,
    reportes:false,
    gastos:false,
    historialprestamo:false,
    anularventa:false,
    ruta:false,
    anularprestamo:false,
    reimpresion:false,
    eliminargasto:false,
    cobrardetalle:false,
    cobrarlocal:false,
    cobrarruta:false,
    cajachica:false,
    editalmacen:false,
    editproducto:false,
    editinventario:false,
    editglosa:false,
    delprestamo:false,
    veralmacen:false,
    pagoalmacen:false,
    cajageneral:false,
    gastoreporteuser:false,
    reportepago:false,
    resumencontable:false,
    delpago:false,
    preciounitario:false,
    registroMateriaPrima:false,
    registroProveedor:false,
    registroProducto:false,
    almacenCostoSubtotal:false,
    almacenCrearMateriaPrima: false,
    almacenHistorialPago:false,
    empleadoSueldo:false,
    editcajachica:false,
    editcliente:false,
  }
}
